name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Doppler Token
        id: doppler
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "token=${{ secrets.DOPPLER_PRO_TOKEN }}" >> $GITHUB_OUTPUT
          else
            echo "token=${{ secrets.DOPPLER_PRE_TOKEN }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Doppler
        uses: dopplerhq/cli-action@v2
        with:
          doppler-token: ${{ steps.doppler.outputs.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          TAG=$(if [ "$BRANCH" = "main" ]; then echo "latest"; else echo "dev"; fi)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/actions-service:$TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/actions-service:$TAG
