name: Docker Build & Push

on:
  push:
    branches:
      - dev
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: |
          docker build -t ezapater/action-service:${{ steps.vars.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ezapater/action-service:${{ steps.vars.outputs.tag }}
