name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Comprova el codi
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # 3. Instal·la dependències
      - name: Install dependencies
        run: |
          go mod tidy

      # 4. Configura Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Construeix i etiqueta la imatge Docker
      - name: Build Docker image
        run: |
          docker build --build-arg BACKEND_URL=$BACKEND_URL -t my-docker-repo/my-app:${{ github.sha }} .

      # 8. Pujar la imatge Docker
      - name: Push Docker image
        run: |
          docker push my-docker-repo/my-app:${{ github.sha }}
